// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcbgjVguSlQjSai4tccUSUGlO6wadYAZ0',
    appId: '1:969070961040:web:5593a250aa5546ec8d9315',
    messagingSenderId: '969070961040',
    projectId: 'registermpl',
    authDomain: 'registermpl.firebaseapp.com',
    storageBucket: 'registermpl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6neMSxmGVnEmvyT8rsSdwmPeWQ3xc-oQ',
    appId: '1:969070961040:android:b51b4913e4af1cda8d9315',
    messagingSenderId: '969070961040',
    projectId: 'registermpl',
    storageBucket: 'registermpl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4SIRyp4cwKmN7jhhMb_cB_F4pih3QYs',
    appId: '1:969070961040:ios:fe1e83a49ab34a8c8d9315',
    messagingSenderId: '969070961040',
    projectId: 'registermpl',
    storageBucket: 'registermpl.firebasestorage.app',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4SIRyp4cwKmN7jhhMb_cB_F4pih3QYs',
    appId: '1:969070961040:ios:fe1e83a49ab34a8c8d9315',
    messagingSenderId: '969070961040',
    projectId: 'registermpl',
    storageBucket: 'registermpl.firebasestorage.app',
    iosBundleId: 'com.example.register',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcbgjVguSlQjSai4tccUSUGlO6wadYAZ0',
    appId: '1:969070961040:web:cbbfe0cf1fcc16368d9315',
    messagingSenderId: '969070961040',
    projectId: 'registermpl',
    authDomain: 'registermpl.firebaseapp.com',
    storageBucket: 'registermpl.firebasestorage.app',
  );
}
